language: python
python:
  - 2.7

sudo: required

services:
  - docker

git:
  submodules: true

before_install:
  - docker build -t tribeswiki/wiki-service .
  - docker run -itd --name tribes-service -p 5000:5000 tribeswiki/wiki-service
  - docker ps -a
  - docker logs tribes-service

# command to install dependencies
install:
  - echo 'install dependencies...'

script:
  - echo 'Execute shell command...'

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi

notifications:
  slack:
    rooms:
      - tribesworld:dzHBgVIhNFNIzILqXHeswFgt
      # - tribesworld:dzHBgVIhNFNIzILqXHeswFgt#tribes
