language: python
python:
  - 2.7
git:
  submodules: false

# command to install dependencies
install:
- pip install -r requirements.txt

script:
- cd tribes/

notifications:
  slack:
    rooms:
      - tribesworld:dzHBgVIhNFNIzILqXHeswFgt
      - tribesworld:dzHBgVIhNFNIzILqXHeswFgt#tribes
