language: python
python:
  - 2.7

sudo: required

services:
  - docker

git:
  submodules: true

before_install:
  - docker build -t tribes/service .
  - docker run -itd --name tribes-service -p 5000:5000 tribes/service
  - docker ps -a
  - docker logs tribes-service

# command to install dependencies
# install:
# - pip install -r requirements.txt

script:
- cd tribes/

notifications:
  slack:
    rooms:
      - tribesworld:dzHBgVIhNFNIzILqXHeswFgt
      # - tribesworld:dzHBgVIhNFNIzILqXHeswFgt#tribes
