# 身份认证模块

POST http://{{host}}/api/auth/token
Content-Type: application/json

{
    "username": "v-zhidu",
    "password": "12345"
}

###

POST http://{{host}}/api/auth/refresh
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6eyJwYXNzd29yZF9oYXNoIjoiMTIzNDUiLCJpZCI6MSwiYWNjb3VudF9uYW1lIjoidi16aGlkdSJ9LCJpYXQiOjE0OTY3MTgxNDQsIm5iZiI6MTQ5NjcxODE0NCwiZXhwIjoxNDk5MzEwMTQ0fQ.7yhrKJ_yqsapOzFcH_KYV-0TC6WpU_W2AOzmjpSoE8Y"
}

###

# 添加新用户

POST http://{{host}}/api/auth/signup
Content-Type: application/json

{
    "email": "du_zhi_qiang@163.com",
    "name": "v-zhidu",
    "password": "12345",
    "callback_url": "http://baidu.com"
}

###

# 验证邮箱有否有效

GET http://{{host}}/api/auth/verify_email/du_zhi_qiang@163.com