# 获取所有用户
GET http://localhost:5001/users

###

# 添加新用户

POST http://localhost:5001/users
Content-Type: application/json

{
    "name": "v-zhidu"
}

###

# 获取单个用户
GET http://localhost:5001/users/12

###

# 更新用户信息
PUT http://localhost:5001/users/10
Content-Type: application/json

{
    "name": "v-zhidu1"
}

###

# 删除用户信息
DELETE  http://localhost:5001/users/11

